###############################################
###
### This file is generated by txpp. Do not edit.
###
### Input file : ./nanoPtclWall.pre
### Output file: ./nanoPtclWall.in
### Translation: Tue, 05 Apr 2011 10:15:44
### 
###############################################
##########
#
# Import needed modules
#
##########
import sys
sys.path.append(".")
import math
#

NDIM	=	2
__FILE__	=	"./nanoPtclWall.pre"
NX	=	80
NY	=	64
NZ	=	1
DX	=	0.10000000000000001
DY	=	0.10000000000000001
DZ	=	0.10000000000000001
DS	=	0.10000000000000001
PTCLRADIUS_SIZE	=	0.20000000000000001
PTCLRADIUS	=	2
PTCLWIDTH_SIZE	=	0.10000000000000001
PTCLWIDTH	=	1.0
DBUPDATER	=	'off'
DBINTERACTION	=	'off'
DBEFFHAMIL	=	'off'
DBPOLYMER	=	'off'
DBSOLVENT	=	'off'
DBBLOCK	=	'off'
DBPTCL	=	'off'
DBBNDRY	=	'off'
DBPHYSFIELD	=	'off'
DBDEFAULT	=	'off'
DBGRID	=	'off'
DBCOMM	=	'off'
DBIO	=	'off'
DBDECOMP	=	'off'
DBFFT	=	'off'
DBDEFAULT	=	'off'
WALLEDGE_NEGX	=	8.0
WALLEDGE_POSX	=	72.0
WIDTHPARAM	=	1.0
LI_EDGE	=	32.0
RI_EDGE	=	48.0
